name: Unit Tests 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]
  workflow_dispatch: {}
  
permissions:
  actions: write
  contents: write

jobs:
  build:  
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 16
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
                    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: run
      run: |
        dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=/tmp/unit_results.xml"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success()
      with:
        name: Unit Tests            
        path: /tmp/unit_results.xml
        reporter: java-junit    