name: Validation Test Plots

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]
  workflow_dispatch: {}
  
permissions:
  actions: write
  contents: write

jobs:
  build:  
    runs-on: ubuntu-20.04
    
    concurrency:
      group: "pages"
      cancel-in-progress: true      
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root  
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
                  
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: run
      run: dotnet run --project TestConsole/TestsConsole.csproj
     
    - name: run python 
      run: python TestGraphs/report.py   
                  
    - name: Deploy to GitHub pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        clean: false
        branch: gh-pages
        folder: html
        token: ${{ secrets.GITHUB_TOKEN }}
        
