name: Validation Test Plots

on:
  push:
    branches: [ main ]
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened 
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch: {}
  
permissions:
  actions: write
  contents: write
  deployments: write
  pages: write
  
jobs:
  build:  
    runs-on: ubuntu-20.04
    
    concurrency:
      group: "pages"
      cancel-in-progress: true      
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root  
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
                  
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Run tests
      run: |
        source .venv/bin/activate
        dotnet run --project TestConsole/TestsConsole.csproj

    - name: Upload test sets
      uses: actions/upload-artifact@v4
      with:
        name: TestSets
        path: TestComponents/TestSets
        
    - name: Run report generator
      run: |
        source .venv/bin/activate
        python TestGraphs/report.py 

    - name: Get current date
      id: date
      run: |
        echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_ENV

    - name: Upload validation report
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: validation_report
        path: html
        
    - name: Deploy to GitHub pages 🚀
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        clean: false
        branch: gh-pages
        folder: html
        token: ${{ secrets.GITHUB_TOKEN }}
        
